name: Docker build

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: false
        default: "xx"
      home:
        description: 'location'
        required: false
        default: "xx"

env:
  IMAGE: static-site

jobs:
  setup-build-publish-deploy:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check
      run: ifconfig -a
    # Build the Docker image
    - name: Build
      run: docker build -f runs.docker -t test:test .
